### ISSUE TITLE
creator_id not found in projectdata model

### ISSUE THREAD

**Issue by alexiswl** [umccr-illumina/libica#77]
Creator ID was added in API release 2.10, are we able to have a release to cater for this?

**Comment by alexiswl** [comment]
Also happy to wait for the release next week first

**Comment by victorskl** [comment]
Yup. Coming in next release.

https://github.com/umccr-illumina/libica/blob/ec9e5ce82e3eef66910eaf407604706b64354677/libica/openapi/v2/model/data_details.py#L144

**Comment by victorskl** [comment]
Fixed by #84
